version: "3"
services:
  todos-db:
    image: "mariadb:10.5-bionic"
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_DATABASE="todo-list"
      - MYSQL_USER="rest-client"
      - MYSQL_PASSWORD="1234"
    ports:
      - "9003:3306"
  api-service:
    build: "./api"
    environment:
      - NODE_ENV="production"
      - NODE_APP_PORT=80
      - DB_NAME="todo-list"
      - DB_USER="rest-client"
      - DB_PASSWORD="1234"
      - DB_HOST=localhost
      - DB_PORT=9003
    volumes:
      - ./api:/home/node/app
    ports:
      - "9000:80"
    links:
      - todos-db
    depends_on:
      - todos-db
  web:
    image: "php:7.4.2-apache"
    volumes:
      - ./web:/var/www/html
    ports:
      - "9001:80"
    links:
      - api-service
    depends_on:
      - api-service
